
/* ALT + SHIFT + N 			--> NEW RESOURCE 
 * CNTRL + 1 	   			--> QUICK FIX. ADD GETTER/SETTER
 * CNTRL + SHIFT + O 		--> ORGANIZE IMPORTS
 * ALTR + SHIFT + R  		--> RENAME
 * CNTRL + E 				--> SWITCH EDITOR
 * CNTRL + W 				--> CLOSE
 * CNTRL + SHIFT + W	 	--> CLOSE ALL
 * CNTRL + SHIFT + R		--> OPEN RESOURCES
 * CNTRL + M 				--> MAXIMIZE EDITOR
 * CNTRL + SHIFT + X		--> CONVERT TO UPPER CASE
 * ALT + UP OR DOWN ARROR	--> MOVE LINES OF TEXT UP OR DOWN
 * ALT + SHIFT + Z			--> SURROUND CODE WITH VARIOUS STUFF
 * CNTRL + SHIFT + F 		--> AUTO FORMAT
 * ALT + SHIFT + R			--> RENAME VARIABLE, METHOD, OR CLASS
 * CNTRL + L				--> JUMP TO LINE
 * CNTRL + O 				--> VIEW CLASS OUTLINE
 * CNTRL + SHIFT + P		--> JUMP TO THE BEGGINING/END OF {}, [], OR ()
 * CNTRL + SHIFT + L		--> VIEW ALL KEYBOARD SHORTCUTS
 */
